### ISSUE TITLE
Welcome page should open imediately upon install

### ISSUE THREAD

**Issue by matadur** [peterhartree/inbox-when-ready#68]
Installed on 2 different Gmail Chrome profiles and saw the same both times. Welcome tab doesn't get loaded until Gmail itself is refreshed. This can be fixed by refreshing the Gmail tab upon install. 

If I get some time later this week, I'll add this and submit a PR...

**Comment by peterhartree** [comment]
>Welcome tab doesn't get loaded until Gmail itself is refreshed.

Yep, I see this issue too. Fixing this would be a big improvement for onboarding UX – thanks for raising it.

> This can be fixed by refreshing the Gmail tab upon install.

Mmm. Maybe we should just open the tab using chrome.runtime.onInstalled as detailed [here](http://stackoverflow.com/a/14957674). 

I didn't actually realise it was possible to refresh all open Gmail tabs on install. If that is do-able, that would be cool, because it would help address another weakness in the current onboarding UX (see #69).

**Comment by peterhartree** [comment]
> If I get some time later this week, I'll add this and submit a PR...

Brilliant. If you do submit a PR you'll probably become the first _not-me_ code contributor to Inbox When Ready :) 

I'll push a quick CONTRIBUTORS.md this evening (#70).
